export const frErrorMessage = {
    AFTER: 'Ce champ doit être postérieur à',
    ALPHA_NUM: 'Ce champ doit être alphanumérique',
    BEFORE: 'Ce champ doit être antérieur à',
    BETWEEN: 'Ce champ doit être entre',
    CONFIRMED: 'Ce champ doit être identique',
    DATE_BETWEEN: 'Ce champ doit être entre les dates spécifiées',
    DATE_FORMAT: 'Ce champ doit suivre le format de date spécifié',
    DECIMAL: 'Ce champ doit être un nombre décimal',
    DIGITS: 'Ce champ doit comporter exactement les chiffres spécifiés',
    EMAIL: 'Veuillez entrer une adresse email valide',
    EXT: 'Extension de fichier non valide pour ce champ',
    IMAGE: 'Seuls les fichiers image sont autorisés pour ce champ',
    INCLUDED: 'Ce champ doit être une des valeurs autorisées',
    INTEGER: 'Ce champ doit être un nombre entier',
    LENGTH: 'La longueur de ce champ doit être',
    MAX_VALUE: 'Ce champ ne doit pas dépasser la valeur maximale spécifiée',
    MIN_VALUE: 'Ce champ doit être au moins égal à la valeur minimale spécifiée',
    EXCLUDED: 'Ce champ ne doit pas être une des valeurs exclues',
    NUMERIC: 'Ce champ doit être une valeur numérique',
    REQUIRED: 'Ce champ est requis',
    URL: 'Veuillez entrer une URL valide',
    AVAILABLE_QUANTITY: 'Cette quantité est supérieure à la quantité disponible.',
    PHONE_OR_EMAIL: 'Email ou numéro de téléphone non valide',
};

export const enErrorMessage = {
    AFTER: 'This field must be after',
    ALPHA_NUM: 'This field must be alphanumeric',
    BEFORE: 'This field must be before',
    BETWEEN: 'This field must be between',
    CONFIRMED: 'This field must be confirmed',
    DATE_BETWEEN: 'This field must be between the specified dates',
    DATE_FORMAT: 'This field must follow the specified date format',
    DECIMAL: 'This field must be a decimal number',
    DIGITS: 'This field must have exactly the specified digits',
    EMAIL: 'Please enter a valid email address',
    EXT: 'Invalid file extension for this field',
    IMAGE: 'Only image files are allowed for this field',
    INCLUDED: 'This field must be one of the allowed values',
    INTEGER: 'This field must be an integer',
    LENGTH: 'The length of this field must be',
    MAX_VALUE: 'This field must not exceed the specified maximum value',
    MIN_VALUE: 'This field must be at least equal to the specified minimum value',
    EXCLUDED: 'This field must not be one of the excluded values',
    NUMERIC: 'This field must be a numeric value',
    REQUIRED: 'This field is required',
    URL: 'Please enter a valid URL',
    AVAILABLE_QUANTITY: 'This quantity is greater than the available quantity',
    PHONE_OR_EMAIL: 'Invalid email or phone number',
};